// await LinqSamples.AsyncSamples();
// LinqSamples.LeftRightJoinSample();
// await LinqSamples.EFLeftRightJoinSample();
// JsonSamples.JsonIgnoreWhenReadWriteSample();
// JsonSamples.JsonIgnoreWithGeneratorTest();
// IPAddressSample.IsValid();
// StringComparerSample.MainTest();
// LinqSamples.ShuffleSamples();
// StringComparerSample.MainTest();
// RandomSample.RunBenchmark();
await AspNetCoreSample.MinimalApiValidation();
